# Generated by Django 5.0 on 2023-12-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_usertasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTasks',
        ),
    ]
